### ISSUE TITLE
VCF file 'Format' and 'Sample' columns

### ISSUE THREAD

**Issue by skambha6** [vahidAK/NanoMethPhase#1]
Hi,

I have a VCF file that doesn't have the optional 'Format' and 'Sample' columns, so a result of running nanomethphase phase I get the following error:
NanoMethPhase selected output format(s): bam
Traceback (most recent call last):
  File "/home-4/skambha6@jhu.edu/.local/bin/nanomethphase", line 10, in <module>
    sys.exit(main())
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/nanomethphase/__main__.py", line 1996, in main
    args.func(args)
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/nanomethphase/__main__.py", line 709, in main_phase
    vcf_dict = vcf2dict_phase(vcf_file,args.window)
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/nanomethphase/__main__.py", line 549, in vcf2dict_phase
    if line_list[9].startswith('1|0') or line_list[9].startswith('0|1'):
IndexError: list index out of range

Is it possible to adjust the way vcf2dict_phase reads in the vcf file to not rely on the 'Format' or 'Sample' columns without hindering any of the downstream phasing?

Thank you!
Sandeep

**Comment by vahidAK** [comment]
Hi @skambha6 ,
Is you vcf file already been phased?
We require the file column to be like:
chr10_GL383545v1_alt    15433   .       A       C       839.407 .       .       GT:GQ:DP:AF:PS  0|1:1080:12:0.4167:15404

Note that the phase information on the 10th column must be indicated by "|" (e.g. "0|1").

Could you send me some lines from your vcf file?

Thanks,
Vahid

**Comment by skambha6** [comment]
Hi Vahid,

Here are the first few lines of my VCF file:
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    3000444 .       T       A       .       .       .       chr1:3000444
chr1    3000608 .       T       G       .       .       .       chr1:3000608
chr1    3000748 .       T       TT      .       .       INDEL   chr1:3000750
chr1    3000748 .       T       TT      .       .       INDEL   chr1:3000751
chr1    3000748 .       T       TT      .       .       INDEL   chr1:3000752`

This VCF file was generated by running MUMMER on two completely homozygous genomes (collaborative cross mice genomes) and converting the resulting .delta file to a VCF file. My sample is a cross between these two homozygous parent mice. Since I know my haplotypes a priori (because the parents are entirely homozygous), would it be sufficient to manually add in a 0|1 for each variant in the sample column?

Thank you for your help!

Best,
Sandeep

**Comment by vahidAK** [comment]
Yes you can manually add 1|0 or 0|1 as 10th column to your file. For example, assign paternal SNVs as 0|1 and Maternal as 1|0. Using this file, NanoMethPhase will give you HP1 (Maternal) and HP2 (Paternal).

**Comment by skambha6** [comment]
Ok, great. Thank you!
