### ISSUE TITLE
working with Guppy latest version

### ISSUE THREAD

**Issue by charliechen912ilovbash** [vahidAK/NanoMethPhase#10]
Thanks for developing this useful tool !
Can I use NanoMethPhase to phase the methylation output from latest version (v6.3.2) of Guppy ?

**Comment by vahidAK** [comment]
Hi @charliechen912ilovbash ,

Currently, you are not able to use it with methylation output from guppy.

Thanks,
Vahid

**Comment by charliechen912ilovbash** [comment]
Will guppy be included as one of the input file source in the future?

**Comment by vahidAK** [comment]
Not in the near future.

**Comment by charliechen912ilovbash** [comment]
I see, thanks for replying.
