### ISSUE TITLE
Reproduce Fig.4 a-b and Additional file 4.

### ISSUE THREAD

**Issue by liuyangzzu** [vahidAK/NanoMethPhase#11]
Dear author,

Thank you for providing codes of your paper.

I have a small issue to reproduce Fig. 4a-b, and additional file 4. My phased results for two haplotypes are slightly bad than your paper's results.

Here, I only use Nanopolish+Clair + WhatsHap, I haven't use SNVoter. I am not sure if this is the reason. I have no idea of how to apply SNVoter (after Clair, and before WhatsHap) here. If you can provide me some sample script for how to use SNVoter to improve the results, that would be a great help! Thank you!

Best,
Yang

**Comment by vahidAK** [comment]
Hi Yang,

We have provided instructions for SNVoter in its repo (This only works for old Clair that outputs a quality value in the 7th column. Moreover, SNVoter works better on older versions of the guppy (<4.3):

https://github.com/vahidAK/SNVoter

BTW, if you use new guppy and Clair3, SNVoter is not required. For WhatsHap, I also recommend using only high-quality SNVs for phasing.

Best,
Vahid

**Comment by liuyangzzu** [comment]
Thank you very much for your reply, @vahidAK! 

I am using same NA19240 run1 dataset, processed by Clair3+WhatsHap. But I use all SNVs instead of high-quality score. Just as you mentioned, this maybe the reason.
