### ISSUE TITLE
NanoMethPhase with other methylation callers outputs

### ISSUE THREAD

**Issue by Thomas-nj** [vahidAK/NanoMethPhase#13]
Hi @vahidAK ,

Although you have mentioned support for other methylation callers was added in iss5 branch, but I didn't find anything to clone in iss5. Do i miss something or i can just use megalodon outputs directly in nanomethphase.py methyl_call_processor?

Thanks,
Mingtao

**Comment by vahidAK** [comment]
Hi,
You should be able to clone the iss5 with something like:
```
git clone -b iss5 https://github.com/vahidAK/NanoMethPhase.git
```

**Comment by Thomas-nj** [comment]
Thank you so much for the response. I‘m gone try that.

**Comment by vahidAK** [comment]
BTW, @Thomas-nj I have added support for megalodon to NanoMethPhase and released a new version. You can clone the git repo master branch and use the latest version (1.2.0)

**Comment by vahidAK** [comment]
BTW, @Thomas-nj I have added support for megalodon to NanoMethPhase and released a new version. You can clone the git repo master branch and use the latest version (1.2.0)

**Comment by vahidAK** [comment]
Just FYI

**Comment by vahidAK** [comment]
v
