### ISSUE TITLE
phasing in blocks

### ISSUE THREAD

**Issue by weishwu** [vahidAK/NanoMethPhase#16]
My variants called from Nanopore sequencing were phased into a couple thousand blocks. Should I run `nanomethphase.py phase` and then `nanomethphase.py dma` for each of the blocks individually?

**Comment by vahidAK** [comment]
Hi,

Nanomethphase does not consider phased blocks during phasing and you can run nanomethphase using all the phased variants at once. Nanomethphase will output haplotype 1 and 2 methylations which you can use for DMA. 

Just bear in mind that at different blocks the actual parent of origin for haplotypes 1 and 2 might be different and at some blocks, haplotype 1 might be paternal while at some others it might be maternal, and vice versa. Therefore, in case a chromosome is not phased to a single block, the parent of origin for haplotype 1 and 2 methylation is not necessarily consistent across the chromosome while we expect to be consistent inside each phase block.

Vahid

**Comment by weishwu** [comment]
Thanks!

**Comment by weishwu** [comment]
@vahidAK Sorry to bug again. Just a small question: is it OK that my VCF contains both phased (e.g. 0|1) and unphased (0/1) variants? I don't have to tease out the phased ones as the input to `nanomethphase.py phase`, right?

**Comment by vahidAK** [comment]
@weishwu, Yes, it is fine if your vcf has both phased and unphased variants.

**Comment by weishwu** [comment]
Thanks!
