### ISSUE TITLE
Getting haplotype methylome

### ISSUE THREAD

**Issue by BeatrizFaustino** [vahidAK/NanoMethPhase#19]
Hello, I could not understand how the nanomethphase separates into two haplotypes (HP1 and HP2), could you explain to me please?

**Comment by vahidAK** [comment]
Hi,
It basically looks into the input bam and phased vcf file to see how many variants from each haplotype are present in each read. Then, based on some criteria such as --min_variant and --hapratio assigns reads to haplotypes.

**Comment by BeatrizFaustino** [comment]
Thank you for the answer. I have another question, is it possible to generate a functional annotation with the Call_DMR.txt file? if so could you recommend me a program?

**Comment by BeatrizFaustino** [comment]
I beg your pardon for asking one more question, the ReadyForDSS file generated by the DMA module does not have a header of what each column would be, could you also explain it to me please?

**Comment by vahidAK** [comment]
> Thank you for the answer. I have another question, is it possible to generate a functional annotation with the Call_DMR.txt file? if so could you recommend me a program?

Take a look at tools such as bedtools or tabix. You can have an annotation file in a bed format and use these tools to annotate your DMRs with the annotation file.

**Comment by vahidAK** [comment]
> I beg your pardon for asking one more question, the ReadyForDSS file generated by the DMA module does not have a header of what each column would be, could you also explain it to me please?

Columns are:
Chromosom, CpG position, Number of all calls for the CpG (5mC+C), Number of 5mC calls

**Comment by BeatrizFaustino** [comment]
In my table of DMRs I cannot identify which sample I compared belongs to these differentially methylated regions! Does he not compare presence and absence in the group, but the frequencies?

If it's the frequencies, does it use the diff method to compare one sample to another?

**Comment by vahidAK** [comment]
dma module uses DSS R package to perform case (or group 1) Vs control (or group 2) differential methylation analysis (DMA). In your DMR file "meanMethy1" is the mean methylation at DMR for file you provided as --case and "meanMethy2" is the mean methylation at DMR for file you provided as --control.
Please see the DSS R package documentation to read about how it does the two group DMA.
