### ISSUE TITLE
Variant caller for non-human samples

### ISSUE THREAD

**Issue by PengNi** [vahidAK/NanoMethPhase#2]
Hi @vahidAK , 

Do you have any suggestions on calling variants from ONT data of non-human samples? I want to try your pipeline with clair, however clair seems does not work.

Best,
Peng

**Comment by vahidAK** [comment]
Hi @PengNi ,
Have you tried [medaka](https://github.com/nanoporetech/medaka)? It is designed by ONT for specific use on nanopore data.
BTW, some of my colleagues used Clair on non human samples. So it is weird that it did not work for you.
Hope it helps,
Vahid

**Comment by PengNi** [comment]
@vahidAK , thanks very much for your reply. Maybe I didn't try Clair deep enough (only `callVarBamParallel` actually). 

I'll try Clair again, and medaka too.

Best,
Peng

**Comment by DustinSokolowski** [comment]
Hey Peng, Did you end up having some insight on using Clair with non human samples?
Best,
Dustin

**Comment by PengNi** [comment]
@DustinSokolowski , Clair can run on non-human samples. And It now is replaced by Clair3.

Best,
Peng
