### ISSUE TITLE
About the results in dma

### ISSUE THREAD

**Issue by isnmn** [vahidAK/NanoMethPhase#21]
Hi,
Are the DMR/DML outputs' columns pval type? For example, when analysing should we consider diff.Methy column as pval?

**Comment by vahidAK** [comment]
Hi @isnmn ,

DMR (differentially methylated region) file does not have a p-val column. However, CpGs that met the p-value threshold you have given to the dma module are used to generate DMRs based on other options you have specified.
diff.Methy column is just the difference of methylation between your comparisons (diff.Methy=meanMethy1-meanMethy2).

DML (differentially methylated loci/CpGs) file has p-value column and only significant CpGs are included in the DML file.

For more details about the output files from dma module you can read the DSS R package [documentation](https://bioconductor.org/packages/release/bioc/manuals/DSS/man/DSS.pdf).

**Comment by isnmn** [comment]
Hi,
How can I have the .bed file of DML and DMR files?

**Comment by vahidAK** [comment]
Hi,
The first three columns of the DMR file include chromosome, start, and end which is like the basic bed format.
In the DML file, the second column is basically the CpG position and you can make a new column by for example adding one base per (column 2 + 1) to column 2 and making a new column as your third column which will represent a basic bed like format (chromosome, start, end).

**Comment by bf004** [comment]
When i put more than one sample into the DMA module, how can I identify each sample in the DMR output? or is it not possible and only shows the differentially methylated regions between all samples?

**Comment by vahidAK** [comment]
It does not output per-sample results. When multiple samples are given it kind of compares the mean from all samples given as cases against the mean of all samples given as controls. In the output DMR file  "meanMethy1" is the mean methylation at DMR for file(s) you provided as --case and "meanMethy2" is the mean methylation at DMR for file(s) you provided as --control. You can read more about two-group differential methylation analysis in the [DSS](https://bioconductor.org/packages/release/bioc/manuals/DSS/man/DSS.pdf) documentation
