### ISSUE TITLE
Installing NanoMethPhase

### ISSUE THREAD

**Issue by olaraym** [vahidAK/NanoMethPhase#22]
Hi @vahidAK thank you for this great resource. However, I have been having difficulties installing the tool. If I run the creation of the environment and installing dependencies using the .yaml file it takes forever and nothing happens

**Comment by vahidAK** [comment]
Hi @olaraym 
Not sure why that happened. Can you please create an environment manually and activate it and then install the dependencies that are in the .yaml file one by one in that environment and see if it works?

Thanks,
Vahid

**Comment by olaraym** [comment]
Thanks @vahidAK It is working now. I will get back to you if I need any more clarity, particularly with the output.
