### ISSUE TITLE
Could modbam2bed output files be used as input methylation call files?

### ISSUE THREAD

**Issue by CWYuan08** [vahidAK/NanoMethPhase#23]
Hi, I am wondering if the pipeline is compatible with modbam2bed output files, thank you very much!

**Comment by vahidAK** [comment]
Hi @CWYuan08 ,
If your bam is a haplotagged bam you can get phased methylation from modbam2bed itself. If you want to use the DMA module to do differential methylation analysis, your inputs need to have the columns needed by this module, and if your files have these columns you should be able to use this module.
