### ISSUE TITLE
Does NanoMethPhase support Clair3?

### ISSUE THREAD

**Issue by PanZiwei** [vahidAK/NanoMethPhase#3]
Hi,
I noticed that Clair3 (https://github.com/HKU-BAL/Clair3) is released recently. Does NanoMethPhase is compatible with the latest Clair? Or it should stick to Clair2 for reproduction?

**Comment by vahidAK** [comment]
Hi @PanZiwei ,

Yes, it does not matter which variant caller you are using. You can use any variant caller and your variants can come from any source.
As NanoMethPhase requires the vcf file to be phased, the thing that matters is that the output of your phased vcf file is compatible with the tool (discussed in issue #1). 
So, it also does not matter which tool you are using afterwards to phase the variants as long as the format is correct (in our work we used WhatsHap and it works very well. So if you use whatshap the vcf is already in the format required by NanoMethPhase).

BTW, I have recently added an [image](https://github.com/vahidAK/NanoMethPhase/blob/master/docs/images/NanoMethPhaseFlowChart.png) to the readme file that represents a nice visualization workflow of the steps that need to be done to get phased methylome.

Let me know if you had any questions,
Vahid

**Comment by PanZiwei** [comment]
If I understand it correctly, the variant caller is no longer in need if I directly use Clair inside the NanoMethPhase docker image, right? 
Thank you in advance for your reply!

**Comment by vahidAK** [comment]
You can use your local installed version of Clair or any variant caller. No need to use Clair installed along NanoMethPhase.
For singularity, my colleague, @garantjm,  can help you.

Yes, If you follow the workflow you will have allele-specific methylation along with several other useful outputs.

Vahid

**Comment by PanZiwei** [comment]
Thank you so much for your quick response. 

I will first have a try on the docker image for convenience. I will first close the issue and will reopen it or create a new issue if it is relevant to the image usage.

**Comment by PanZiwei** [comment]
I successfully install it via the singularity.
