### ISSUE TITLE
How do you upload nanopore raw fast5 to EGA? 

### ISSUE THREAD

**Issue by PanZiwei** [vahidAK/NanoMethPhase#4]
To whom it may concern,
**How do you upload nanopore raw fast5 files to EGA** since EGA doesn't support .fast5 files? 

In the paper you claimed that “… nanopore raw fast5 and basecalled fastq files for the Colo829BL sample are available at the European Genome-phenome Archive under the accession number EGAS00001001385”.  I checked the EGAS00001001385 but it didn't display the data format. 

I tried to use PacBio HDF5, but got the error when filling out the metadata online:
“Submission 6144993798e2520001e4ce13: In run, alias:“073156dc-823b-41ce-a853-ed7221a468e1”, accession:“”, In filename:“EGA_submission_encrypted/sample.batch_1.fast5”, filetype:“PacBio_HDF5". Invalid file suffix for file type “PacBio_HDF5”. Supported file suffixes for this file type are: .h5,.xml.”

![Screen Shot 2021-09-17 at 7 17 14 PM](https://user-images.githubusercontent.com/44417006/133867017-79a4691c-6039-4d51-b5c8-a358e5e0339e.png)

![image](https://user-images.githubusercontent.com/44417006/133867267-2768ddfb-04d2-4c33-b362-f3e7c1c4cab9.png)

My apology in advance that the question is more relevant to the data availability instead of the software itself.

Thank you so much for your help!!

Best,
Ziwei

**Comment by vahidAK** [comment]
Hi @PanZiwei ,

The data  is in EGA EGAS00001001385 under datasetID EGAD00001007920 :
![image](https://user-images.githubusercontent.com/46334063/133867717-1858b47c-0250-4343-b5cd-66c09fdf010a.png)  

EGA is a controlled access repo and this might be the reason you cannot see the data format. They have recently started to accepting the Fast5 format. I did not personally submit the data and my colleague did that, but I think if you follow [this guide](https://ega-archive.org/submission/quickguide) you should be able to submit your data. I will also check with my colleague.

I recommend you contact the EGA help desk at "ega-helpdesk@ebi.ac.uk" to get help with uploading your data.

Best,
Vahid

**Comment by PanZiwei** [comment]
Hi @vahidAK 
Thank you so much for your reply! Actually, I clicked the dataset but nothing relevant to the data format displayed. I also checked the tutorial link you sent before but it didn't help a lot, and I also emailed the EGA help desk but they are offline during the weekend but we are a little bit urgent.  I also checked other Nanpore datasets on EGA but their data format is also unavailable like yours...

Anyway, EGA submission is really horrible. Would really appreciate it if you can get some hints from your colleague!

**Comment by vahidAK** [comment]
Hi @PanZiwei ,

I've asked my colleague but she did not respond yet. As soon as I hear from her will let you know.

Thanks,
Vahid

**Comment by PanZiwei** [comment]
Hi @vahidAK 
Thank you so much for your help! Right now we are trying to change .fast5 into .h5 and also tried the ont2cram(https://github.com/EGA-archive/ont2cram) to convert fast5 to cram. Hopefully one of them can work. 

Will keep you posted also.

Thanks again for your help!

Best,
Ziwei

**Comment by PanZiwei** [comment]
Hi @vahidAK 
I got the update from EGA helpdesk and was told that "Oxford Nanopore native data must be submitted as a single tar.gz archive containing basecalled fast5 files. In this case, please group the files into a tar.gz ( It is fine to include a directory
structure within the TAR ). " In this case I will follow their instruction and close the ticket.

Thank you so much for your help!

Best,
Ziwei

**Comment by vahidAK** [comment]
Great! thanks for letting me know, @PanZiwei .

Best,
Vahid
