### ISSUE TITLE
NanoMethPhase compatibility with Megalodon output

### ISSUE THREAD

**Issue by cstill8221992** [vahidAK/NanoMethPhase#5]
Hi, I was wondering if there was a way to use the per_read_modified_base_calls output from Megalodon as the input for the MethylCallfile in the methyl_call_processor function for NanoMethPhase? If not, is there plans to implement this in the future?

Thanks,
Chris

**Comment by vahidAK** [comment]
Hi @cstill8221992 ,
Currently, only nanopolish is supported. But I am working on NanoMethPhase to also include megalodon and deepsignal. I am hoping to finish it in a few next days and update the tool soon. 

I will keep you posted.

Best,
Vahid

**Comment by cstill8221992** [comment]
Thanks Vahid for the quick response.
