### ISSUE TITLE
the index for measuring DMR

### ISSUE THREAD

**Issue by charliechen912ilovbash** [vahidAK/NanoMethPhase#8]
Hi,
Is there any value for measuring how different between the `case` and `control` of each DMR except for p-val ?
Some value in the `diff.Methy` column in the `XX_callDMR.txt` is quite small, between -0.01 and 0.01, is this normal?
Thanks

**Comment by vahidAK** [comment]
Hi,
I think you might see such a very low methylation difference but should be very rare I think. 
Basically, you can also filter based on the areaStat and diff.meth in the callDMR file. I think it would make sense to remove regions with very low diff.meth for example regions with diff.meth between -0.2 and 0.2.

Best,
Vahid

**Comment by charliechen912ilovbash** [comment]
Yes, those cases are very rare.
I see, is the filtering criteria you mentioned "`diff.meth` between -0.2 and 0.2" only for the default p value (0.001)?

**Comment by vahidAK** [comment]
Yes, but I think the choice of methylation difference should not be much dependent on pvalue. This methylation difference is basically the difference between the average methylation at your case and average of methylation at your sample for that region.
Try to select the best methylation difference that is best for your study

**Comment by charliechen912ilovbash** [comment]
I see, thanks very much.

**Comment by charliechen912ilovbash** [comment]
Are the `meanMethy1` and `meanMethy2` beta value?

**Comment by vahidAK** [comment]
Yes, you can also have a look at DSS R package for more documentation. We use this package for differential methylation analysis
